### ISSUE TITLE
Make it easier to utilize the XML parsing from within other projects

### ISSUE THREAD

**Issue by wtimme** [holyturt/SwiftOverpassWrapper#14]
### Use Case
I'm currently working on a framework to query the [OpenStreetMap API v0.6](https://wiki.openstreetmap.org/wiki/API_v0.6), and would like to utilize the XML parsing that _SwiftOverpassWrapper_ is already doing.

### The Issue

I added the framework to my dependencies, but quickly noticed that I am not able to benefit from our unit-tested XML parsing, since the conversion from `Data` to an `AEXMLDocument`, followed by enumerating all the objects from the `DataResponse` is hidden in the hidden initializer of `OverpassResponse`:

```swift
internal init(response: DataResponse<String>, requestQuery: String) { }
```

### Improve `OverpassResponse`

`OverpassResponse` doesn't seem like a bad place to do the parsing of an XML response. A few properties, however, are of no use to me, namely

- `requestQuery` and
- `xml`

By removing `requestQuery`, we remove the need to pass it to the initializer:
```swift
internal init(response: DataResponse<String>) { }
```

Let's have a look at how the `response` argument is being used:
```swift
self.xml = String(data: response.data!, encoding: String.Encoding.utf8)!
let xmlDoc = try AEXMLDocument(xml: self.xml)
```
So what we _actually_ need is the XML `String` - let's update the initializer to reflect that:
```swift
internal init(xml: String) { }
```

Now all we need to do is make the initializer publicly accessible:
```swift
public init(xml: String) { }
```

Besides making the XML parsing available publicly, this would allow us to finally unit test that last bit of the response: combined lists of nodes, ways and relations. What do you think, @holyturt?

**Comment by holyturt** [comment]
Throwing `Error` is what I wanted. I definitely would like to adopt it!
These properties, `requestQuery` and `xml`, are made for checking actual query and response when the API returns errors but it seems inappropriate for here and is for developers of this project rather than users.
I think such properties have to move into `Error` if they are needed. Therefore they should be removed from `OverpassResponse` and make the initializer have the response only.
What do you think, @wtimme?

**Comment by holyturt** [comment]
Making the publicly accessible is looks great! We need testability. 😉

**Comment by wtimme** [comment]
I've responded to your suggestion over at the pull request (#15). Once it is merged we can close this issue. 👍
