### ISSUE TITLE
Add OpenStreetMap API client to this repository?

### ISSUE THREAD

**Issue by wtimme** [holyturt/SwiftOverpassWrapper#21]
Today I met the author of [StreetComplete][1], @westnordost. I told him about _SwiftOverpassWrapper_ and my efforts to create a basic client for OpenStreetMap's REST API v0.6. He suggested to consider adding the functionality to the _SwiftOverpassWrapper_ repository.

What do you think, @holyturt?

[1]: https://github.com/westnordost/StreetComplete

**Comment by holyturt** [comment]
Wow that's cool!  I'm glad to hear that. Thank you for sharing, @wtimme!
It sounds this library become more flexible thanks to the API client and more challenging project. 😁
I'm curious about his suggestion. Could you share any further ideas of containing the API client?
Thanks in advance!

**Comment by wtimme** [comment]
I've already started implementing some of the methods, but this is basically what my client is capable of.

```swift
public protocol APIClientProtocol {
    
    /// Flag whether the client is authenticated.
    var isAuthenticated: Bool { get }
    
    /// Removes the credentials, logging the client out.
    func logout()
    
    /// Authenticates the client by presenting a view controller with the OAuth flow.
    /// When successful, the client stores the credentials in the Keychain and is authenticated.
    ///
    /// - Parameters:
    ///   - presentingViewController: The view controller from which the OAuth flow should be presented.
    ///   - completion: Closure that is executed once the process has finished.
    func addAccountUsingOAuth(from presentingViewController: UIViewController,
                              _ completion: @escaping (Error?) -> Void)
    
    /// Request the list with permissions from the server.
    ///
    /// - Parameter completion: Closure that is executed once the permissions were determined or an error occured.
    func permissions(_ completion: @escaping ([Permission], Error?) -> Void)
    
    /// Attempts to download the map data inside the given bounding box.
    ///
    /// - Parameters:
    ///   - boundingBox: The bounding box that confines the map data.
    ///   - completion: Closure that is executed once the map data was downloaded completely or an error occured.
    func mapData(inside boundingBox: BoundingBox, _ completion: @escaping ([OverpassElement], Error?) -> Void)
    
}
```

I'm implementing the methods as I go and when I need them. You can find [the methods of API version 0.6 in the OSM wiki][1].

What do you think? Should we try to cover the API in this project as well, or should we/I rather create a new project?

[1]: https://wiki.openstreetmap.org/wiki/API_v0.6#API_calls

**Comment by holyturt** [comment]
Looked at the page and the code, I thought that there is only one common point between _SwiftOverpassWrapper_ and _OpenStreetMap API client_: the **models**, entities of OSM data. 
This is because one is optimized for data fetching, and the other is for comprehensive functions. Furthermore, the endpoints they access aren't the same protocol.
Therefore, it is worth to consider dividing _SwiftOverpassWrapper_ into two and creating new project for _OpenStreetMap API client_ like the way you told (in #20). Having compatible models seems nice, though. 😉

This is my opinion so far. I might have missed some aspects due to lack of knowledge of _OpenStreetMap API_.
What do you think, @wtimme?

**Comment by wtimme** [comment]
Yes, I agree with you. Even though a "one-fits-all" solution would be great in theory, I think having frameworks that serve one _dedicated_ purpose is a better idea, because of the clear focus.

Furthermore, I think that with the implementation of #17, I could simply utilize a Subspec and avoid including the whole Overpass overload.

Thanks for your thoughts and input! 👍
