### ISSUE TITLE
Complete Models?

### ISSUE THREAD

**Issue by Lelelo1** [holyturt/SwiftOverpassWrapper#26]
Is the models used complete for any json object that overpass returns? If so is there a offical json that contains all possible return values somewhere - or can I used the [swiftModels](https://github.com/holyturt/SwiftOverpassWrapper/tree/master/SwiftOverpass/Models) as reference in my C# project and assume it's complete?

**Comment by wtimme** [comment]
Hi, if you're looking for a reference, I suggest you check out the OSM wiki pages on the [elements](https://wiki.openstreetmap.org/wiki/Elements) and the [API](https://wiki.openstreetmap.org/wiki/API_v0.6).
