### ISSUE TITLE
Unable to retrieve data for `meta` verbosity

### ISSUE THREAD

**Issue by wtimme** [holyturt/SwiftOverpassWrapper#4]
## Steps to reproduce:
```
// 1. Create an `OverpassQuery`
let query: OverpassQuery = ...

// 2. Create an `OverpassAPI`
let api: OverpassApi = ...

// 3. Fetch data using `OutputVerbosity.meta` 
api.fetch(query, verbosity: .meta) { response in
    // Handle the response
}
```
`response.nodes` contains a list of `OverpassNode` objects.

## Observed behaviour
Unfortunately, when parsing the response XML, meta information (e. g. `version`) is thrown away and cannot be accessed using the `OverpassNode`.

## Expected behaviour
`OverpassNode` should contain the meta information from the response.

**Comment by wtimme** [comment]
This could be solved in several ways.

## Subclassing `OverpassNode`
`OverpassNode` would contain only the very basic information of a node.
A subclass (e. g. `DetailledOverpassNode`) could contain additional properties that stem from the `meta` verbosity.

## Optional `meta` property
As the meta output verbosity adds optional details to a node, it can be wrapped in a dedicated object (e. g. `OverpassMeta`).
Do you have experience with ways? Is the content of the meta output the same for them, or does it differ from nodes?

For simplicity's sake, I would opt for the second option. Subclassing feels like overhead.
What do you think?

**Comment by wtimme** [comment]
In my fork, I've added [the `meta` property](https://github.com/wtimme/SwiftOverpassWrapper/blob/feature/Meta-properties-WIP/SwiftOverpass/OverpassEntity.swift#L13) to the `OverpassEntity` superclass and adjusted the XML parsers accordingly. For my use case, it's working as expected.
Please note that my branch depends on [the pull request for adding tests](https://github.com/holyturt/SwiftOverpassWrapper/pull/5), as it adds tests for the meta information. I'd rebase my changes and create a dedicated branch and pull request once the PR is accepted.

What do you think? Is the `Meta` object the way to go? Thanks in advance for your feedback!

**Comment by holyturt** [comment]
I'm agree with the second idea, wrapping meta property in the `Meta` object. Subclassing seems too much and I think it requires casting for each response to access meta.
I've only used `body` for my app but maybe [several content of the `meta` may have different value (e. g. user, uid)](http://overpass-turbo.eu/s/zGk).
Anyway, I prefer the second one too and it will work!

**Comment by wtimme** [comment]
Hey @holyturt,

Thanks for your feedback! I absolutely agree and have added support for these attributes with #6.
It proved a bit difficult to hunt down details on the attributes available, but I'm certain that all entities share the same meta attributes:

- `version`
- `changesetId`
- `timestamp`
- `userId`
- `username`

The timestamp is still a `String`, since I'm not using this information at the moment. But as you can tell [from the parser](https://github.com/wtimme/SwiftOverpassWrapper/blob/feature/Add-support-for-meta-attributes/SwiftOverpass/Extensions/OverpassEntity%2BAEXMLElement.swift#L33), it'd be fairly easy and straight-forward to parse it to a `Date` later down the road.

**Comment by holyturt** [comment]
Thanks for the PR! Your assumption seems correct, if [the official document](https://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide#Verbose_.28meta.2C_meta.29) is right. 😛
Collecting the timestamp as a `String` is also good for the performance. I think it is the way to go. I will merge that!
